### ISSUE TITLE
Private key in terraform.state file?

### ISSUE THREAD

**Issue by qingvincentyin** [DNXLabs/terraform-aws-client-vpn#12]
### Summary

Consider this block of code:

- https://github.com/DNXLabs/terraform-aws-client-vpn/blob/29f1f5e87f3e80c039505d5069e0a4fd6b022213/acm-certificate-server.tf#L1-L3

According to [Terraform docs](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key), the generated private key will be stored in cleartext in the `terraform.state` file.

It would be better if this module optionally accepts an existing private key (in fact, the privkey, pubkey, and optionally a parent CA cert to be complete) or a name/ARN of an existing cert in ACM -- and only falls back to the auto-generated privkey if none of those are passed in. That will make this more production strength.

### Motivation

Avoid putting secrets into the `terraform.state` file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adenot** [comment]
agree with your assessment but it's not something we are looking to implement at this moment, feel free to send PR if you have this implemented in your fork.
