### ISSUE TITLE
Minor issue with Docs

### ISSUE THREAD

**Issue by mickeypash** [DNXLabs/terraform-aws-client-vpn#15]
### Description. What happened?

Hi there!

Not sure why but the `vpc_id` required variable isn't referenced in the latest version of the [doc](https://registry.terraform.io/modules/DNXLabs/client-vpn/aws/latest) but it is in the README.

There must be something wrong with the publishing process?
I checked the Github Actions and it looks like everything ran successfully

### Steps to reproduce

- Visit the [Terraform Repository link](https://registry.terraform.io/modules/DNXLabs/client-vpn/aws/latest)
- Look for `vpc_id` in the table contents
- Currently it is not there
- Check the README.md where you will find it mentioned as a required var

### Actual behavior

Maybe it's an issue with the https://github.com/DNXLabs/terraform-docs config?

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adenot** [comment]
I believe this has been fixed as vpc_id is showing in the docs as required.
